### ISSUE TITLE
evaluation script only supports jaccard index

### ISSUE THREAD

**Issue by mbjorner** [cpsiff/plant-segmentation#2]
other sklearn metrics include the [dice coefficient](https://en.wikipedia.org/wiki/S%C3%B8rensen%E2%80%93Dice_coefficient) (as [F1 score](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.f1_score.html#sklearn.metrics.f1_score)), which we could lump in with [precision and recall](https://scikit-learn.org/stable/modules/generated/sklearn.metrics.precision_recall_fscore_support.html#sklearn.metrics.precision_recall_fscore_support) while we're at it.

**Comment by cpsiff** [comment]
Added dice coefficient, I did not add precision and recall b/c it seems a bit redundant with dice coefficient, and we probably don't want to display three different measures in the final paper anyway. #3
